-- Drop doc_team_path: the same three columns, in the same order, as the primary key.
--
-- 006 added it "so a reindex can delete rows whose file no longer exists, scoped to one
-- team". That query needs an index on (team_slug, …) and one already existed: 001 declares
-- `primary key (team_slug, initiative, path)`, and Postgres builds a unique btree for it.
-- So the table has carried two identical btrees ever since, and every document write has
-- maintained both.
--
-- It is not unused — the planner had been choosing it, 12,057 scans against doc_pkey's 781,
-- which is exactly what makes it easy to keep by mistake. Usage says which of two equivalent
-- indexes the planner picked, not that both were needed.
--
-- Verified before writing this, inside a transaction that was rolled back: with
-- doc_team_path dropped, both shapes the reindex and the write path use — the full key
-- lookup and the team-prefix scan — plan as `Index Only Scan using doc_pkey` with the same
-- Index Cond they had before. Same plan, one fewer index to write.
--
-- doc_team_type, doc_tsv, doc_tags and doc_evidence are NOT duplicates of anything and stay,
-- for the reasons 008 sets out.
drop index if exists zz.doc_team_path;
