-- Drop `comment`: a second route to an effect the platform already had one route for.
--
-- A comment and a source were the same thing wearing two names — somebody's words about a
-- document, arriving from outside the flow. They cost differently, which is the problem: a
-- source bumps the document to the next version, is linked from the envelope, and is frozen
-- into _versions/ with the approval it changed. A comment did none of that. So whether "B
-- says this requirement is wrong" became part of the record depended on which door B walked
-- through, and the cheaper door was the one that left no trace in the document's history.
--
-- The web view did not lose the affordance. A person still writes on a document from their
-- phone; it now lands as a source on the initiative, attached to that document, through
-- zz-core like every other write. Resolution needs no column: the next version, and the
-- source it cites, are what "addressed" means and are already visible.
--
-- Rows are dropped rather than converted. A conversion would have to invent an author's
-- intent — which comments were material that should have changed a document, and which were
-- asides — and a source that says something its author did not is worse than a lost aside.
drop table if exists zz.comment;
