-- WHICH BUILDING BLOCKS AN INITIATIVE CHOSE, on the row rather than only in the file.
--
-- A flow stage may declare `blocks: "selected"` — it calls whatever the initiative's own
-- selection document names — and the gateway resolves that on every block call. It has no
-- access to the team's file store, so it reads zz.doc, and zz.doc keeps the body with the
-- envelope already stripped. The field was written, stored, and unreadable by the one
-- component that exists to read it: the resolution fell through to "unknown", which is
-- unenforced, and every stage after selection could call anything again.
--
-- text[], like tags and evidence beside it, because a selection is a small set and the
-- readers ask "is casebox in it".
alter table zz.doc add column if not exists blocks text[] not null default '{}';
