-- zz.initiative.closed_at IS WRITTEN BY NOTHING, AND IT READS AS AN ANSWER.
--
-- 017 declared it. Nothing has set it since — not `close()`, not the ledger append, not any
-- backfill. `grep -rn closed_at services packages scripts` finds exactly one hit, and it is
-- 017's own CREATE TABLE. Measured on the deployment on 2026-09-13: eleven initiatives, two of
-- them genuinely closed, and `closed_at` NULL on all eleven.
--
-- ── WHY THIS IS WORTH A MIGRATION RATHER THAN A SHRUG ───────────────────────────────────
--
-- A column nobody writes is harmless right up until somebody reads it, and this one is named
-- exactly like the question people ask of it. It was read on 2026-09-13, by an agent asking
-- which initiatives were closed, and it answered "none of them, ever" — confidently, across
-- both teams, in a table that looked complete. The console was showing `accepted` and
-- `delivered` on the same screen at the same moment. The person had to point at their own
-- screen to correct the machine.
--
-- That is the whole failure mode: not a wrong value, an EMPTY one that is indistinguishable
-- from a true negative. `zz.run.outcome` was dropped in 048 for precisely this shape, and its
-- header said it in a line worth repeating here: "a column reserved for a decision nobody makes
-- is a column that reads as a fact somebody forgot to record."
--
-- ── WHERE A CLOSE ACTUALLY LIVES, so nothing has to be reconstructed ────────────────────
--
-- `close()` writes two things and neither of them is here:
--
--   1. the OUTCOME onto the flow's closing document — `zz.doc.outcome` on the document the
--      manifest declares as closing (spec.md for sdlc-flow), as `delivered` or `accepted`,
--      derived by the platform from the disposition and whether anybody signed off;
--   2. a row on the team's `_ledger.md`, which is what the ledger is counted from.
--
-- The console's state column reads the first of those and is correct. So this is not a gap
-- being papered over — the close is recorded in two places already, and a third would be a
-- third answer to one question, which is the shape this repository keeps removing rather than
-- adding to.
--
-- A timestamp for the close is not lost with the column: the ledger row carries the date, and
-- the closing document's own `updated_at` moves when the outcome is stamped onto it. If a
-- precise closed-at instant is ever genuinely wanted, it belongs on the document beside the
-- outcome that already lives there, written in the same statement — not in a second table that
-- can disagree.
--
-- NOTHING READS IT. Verified across services/, packages/, scripts/, checks/ and the console
-- repository before writing this. There is no reader to update and nothing to migrate: every
-- value in the column is NULL, so no close is being destroyed here — the column never held one.

alter table zz.initiative drop column if exists closed_at;
