-- A token carries whatever its holder may do, so there is nothing for this column to say.
--
-- `pat.scope` was 'member' or 'admin' and authority checks asked the TOKEN what its holder
-- could do: isSuper() required scope='admin' before it would believe a superadmin, isTeamAdmin()
-- refused a member-scope token outright, and operatorOnly() refused it again. So the same person
-- was allowed or forbidden the same act depending on which of their credentials they happened to
-- be holding, and the cure for being refused was to go and mint a second token — which is a
-- second thing to rotate, a second to revoke, and one of them quietly stale.
--
-- Authority is a fact about a PERSON. It lives on `principal.role` and in `membership`, both of
-- which every check already reads. A credential that grants less than its holder has is a
-- credential that lies about them, and the lie is only discoverable by being refused something
-- you are in fact allowed to do.
--
-- WHAT IS NOT DROPPED: `pat.team_id`. Binding a token to one team answers a different question —
-- which team this token acts INSIDE — and confining the team somebody acts for is not a claim
-- about what they are permitted to do. `resolvePat` still narrows memberships by it.
--
-- NO BACKFILL AND NOTHING TO PRESERVE: the column is read by nothing after this release. Six
-- live tokens carried a value; all six now carry their holder's own authority, which is what
-- their holders always had.
alter table pat drop column if exists scope;
