/**
 * Generated by `scripts/schema-target-extract.ts` — part 5 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_5: Record<string, TableTarget> = {
  eval_evidence_snapshot: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "observation_snapshot_id",
        "uuid",
        false,
        null,
      ],
      [
        "subject_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "protocol_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "coverage",
        "jsonb",
        false,
        null,
      ],
      [
        "content_digest",
        "text",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "observation_snapshot_id",
        "protocol_version_id",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "observation_snapshot_id",
        ],
        refTable: "eval_observation_snapshot",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "protocol_version_id",
        ],
        refTable: "eval_protocol_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "subject_version_id",
        ],
        refTable: "eval_subject_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_failure_mode_candidate: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "observation_snapshot_id",
        "uuid",
        false,
        null,
      ],
      [
        "stable_key",
        "text",
        true,
        null,
      ],
      [
        "description",
        "text",
        false,
        null,
      ],
      [
        "prevalence",
        "jsonb",
        false,
        null,
      ],
      [
        "owner_kind",
        "text",
        false,
        null,
      ],
      [
        "confidence",
        "numeric",
        true,
        null,
      ],
      [
        "evidence_refs",
        "jsonb",
        false,
        null,
      ],
      [
        "status",
        "text",
        false,
        null,
      ],
      [
        "merged_into_id",
        "uuid",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "merged_into_id",
        ],
        refTable: "eval_failure_mode_candidate",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "observation_snapshot_id",
        ],
        refTable: "eval_observation_snapshot",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((owner_kind = ANY (ARRAY['plugin'::text, 'dependency'::text, 'platform'::text, 'environment'::text, 'user_input'::text, 'unknown'::text])))",
      "CHECK ((status = ANY (ARRAY['candidate'::text, 'accepted'::text, 'rejected'::text, 'merged'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_finding: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "eval_id",
        "uuid",
        true,
        null,
      ],
      [
        "pattern",
        "text",
        false,
        null,
      ],
      [
        "docs_affected",
        "integer",
        false,
        "0",
      ],
      [
        "scope",
        "text",
        true,
        null,
      ],
      [
        "proposed_change",
        "text",
        false,
        "''::text",
      ],
      [
        "decision",
        "text",
        false,
        "'deferred'::text",
      ],
      [
        "resulted_in_skill_version_id",
        "uuid",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "decided_by",
        "text",
        true,
        null,
      ],
      [
        "decided_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "decision_note",
        "text",
        false,
        "''::text",
      ],
      [
        "owner_kind",
        "text",
        true,
        null,
      ],
      [
        "owner_ref",
        "text",
        true,
        null,
      ],
      [
        "measure_id",
        "uuid",
        true,
        null,
      ],
      [
        "evidence_refs",
        "jsonb",
        false,
        "'[]'::jsonb",
      ],
      [
        "expected_effect",
        "jsonb",
        true,
        null,
      ],
      [
        "eval_run_id",
        "uuid",
        true,
        null,
      ],
      [
        "kind",
        "text",
        true,
        null,
      ],
      [
        "superseded_by",
        "uuid",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "eval_id",
        ],
        refTable: "eval",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
      {
        columns: [
          "eval_run_id",
        ],
        refTable: "eval_run",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "measure_id",
        ],
        refTable: "eval_measure",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "resulted_in_skill_version_id",
        ],
        refTable: "skill_version",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
      {
        columns: [
          "superseded_by",
        ],
        refTable: "eval_finding",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((decision = ANY (ARRAY['applied'::text, 'rejected'::text, 'deferred'::text])))",
      "CHECK ((kind = ANY (ARRAY['strength'::text, 'defect'::text, 'unknown'::text])))",
      "CHECK ((owner_kind = ANY (ARRAY['plugin'::text, 'dependency'::text, 'platform'::text, 'environment'::text, 'user_input'::text, 'unknown'::text])))",
      "CHECK (((eval_id IS NOT NULL) <> (eval_run_id IS NOT NULL)))",
      "CHECK (((eval_run_id IS NULL) OR (kind IS NOT NULL)))",
      "CHECK ((scope = ANY (ARRAY['generic'::text, 'specific'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {
      decision_note: "Why it was applied or rejected. Empty while deferred -- the open state needs no reason, and the two closed ones do.",
      eval_run_id: "Set instead of eval_id for an EVALUATE-produced finding (finding_record). Exactly one of the two is non-null.",
      kind: "strength | defect | unknown — required when eval_run_id is set; null on every legacy round finding, which carries scope instead.",
      superseded_by: "The finding that corrected this one, when finding_record(supersedes) replaced it. Null for a current finding. A superseded finding is also decision=rejected, so it stays closed for every reader.",
    },
  },
  eval_idempotency: {
    columns: [
      [
        "principal",
        "text",
        false,
        null,
      ],
      [
        "tool",
        "text",
        false,
        null,
      ],
      [
        "idempotency_key",
        "text",
        false,
        null,
      ],
      [
        "request_digest",
        "text",
        false,
        null,
      ],
      [
        "result_table",
        "text",
        false,
        null,
      ],
      [
        "result_id",
        "uuid",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "principal",
      "tool",
      "idempotency_key",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_measure: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "dimension_id",
        "uuid",
        false,
        null,
      ],
      [
        "key",
        "text",
        false,
        null,
      ],
      [
        "evaluator_type",
        "text",
        false,
        null,
      ],
      [
        "weight",
        "numeric",
        false,
        null,
      ],
      [
        "suite",
        "text",
        false,
        null,
      ],
      [
        "required",
        "boolean",
        false,
        null,
      ],
      [
        "definition",
        "jsonb",
        false,
        null,
      ],
      [
        "evaluator_version_id",
        "uuid",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "dimension_id",
        ],
        refTable: "eval_dimension",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "evaluator_version_id",
        ],
        refTable: "eval_evaluator_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK (((evaluator_type <> ALL (ARRAY['bounded_semantic'::text, 'generative_critic'::text])) OR (evaluator_version_id IS NOT NULL)))",
      "CHECK ((evaluator_type = ANY (ARRAY['deterministic'::text, 'outcome'::text, 'bounded_semantic'::text, 'generative_critic'::text, 'human'::text])))",
      "CHECK ((suite = ANY (ARRAY['capability'::text, 'regression'::text, 'production'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
};
