/**
 * Generated by `scripts/schema-target-extract.ts` — part 6 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_6: Record<string, TableTarget> = {
  eval_observation_snapshot: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "subject_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "production_window",
        "jsonb",
        false,
        null,
      ],
      [
        "coverage",
        "jsonb",
        false,
        null,
      ],
      [
        "usable_run_count",
        "integer",
        false,
        null,
      ],
      [
        "total_run_count",
        "integer",
        false,
        null,
      ],
      [
        "runtime_identity",
        "jsonb",
        false,
        null,
      ],
      [
        "environment_digest",
        "text",
        false,
        null,
      ],
      [
        "evidence_digest",
        "text",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
      [
        "facts",
        "jsonb",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "subject_version_id",
        ],
        refTable: "eval_subject_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {
      facts: "Every ObservedFact computeObservation wrote for this snapshot (observe-facts.ts's OBSERVATION_FACT_KEYS), keyed by fact name. Null when the snapshot carries no computed facts, and every deterministic/outcome measure against it then answers excluded with a named reason. A deterministic/outcome measure reads one entry by dotted definition.factPath.",
    },
  },
  eval_protocol: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "plugin_id",
        "uuid",
        false,
        null,
      ],
      [
        "protocol_key",
        "text",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "plugin_id",
        "protocol_key",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "plugin_id",
        ],
        refTable: "plugin",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_protocol_version: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "protocol_id",
        "uuid",
        false,
        null,
      ],
      [
        "version",
        "integer",
        false,
        null,
      ],
      [
        "subject_compatibility",
        "jsonb",
        false,
        null,
      ],
      [
        "purpose",
        "text",
        false,
        null,
      ],
      [
        "observable_surfaces",
        "jsonb",
        false,
        null,
      ],
      [
        "failure_taxonomy",
        "jsonb",
        false,
        null,
      ],
      [
        "suites",
        "jsonb",
        false,
        null,
      ],
      [
        "qualification_policy",
        "jsonb",
        false,
        null,
      ],
      [
        "scoring_policy",
        "jsonb",
        false,
        null,
      ],
      [
        "improvement_policy",
        "jsonb",
        false,
        null,
      ],
      [
        "content_digest",
        "text",
        false,
        null,
      ],
      [
        "approved_document_path",
        "text",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "protocol_id",
        "version",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "protocol_id",
        ],
        refTable: "eval_protocol",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_run: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "subject_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "protocol_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "evidence_snapshot_id",
        "uuid",
        false,
        null,
      ],
      [
        "run_status",
        "text",
        false,
        null,
      ],
      [
        "score_status",
        "text",
        true,
        null,
      ],
      [
        "overall_score",
        "numeric",
        true,
        null,
      ],
      [
        "score_interval",
        "jsonb",
        true,
        null,
      ],
      [
        "dimension_scores",
        "jsonb",
        true,
        null,
      ],
      [
        "guardrail_status",
        "text",
        true,
        null,
      ],
      [
        "coverage",
        "jsonb",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
      [
        "guardrails",
        "jsonb",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "evidence_snapshot_id",
        ],
        refTable: "eval_evidence_snapshot",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "protocol_version_id",
        ],
        refTable: "eval_protocol_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "subject_version_id",
        ],
        refTable: "eval_subject_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((guardrail_status = ANY (ARRAY['pass'::text, 'fail'::text, 'not_established'::text])))",
      "CHECK ((run_status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])))",
      "CHECK ((score_status = ANY (ARRAY['established'::text, 'provisional'::text, 'not_established'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {
      guardrails: "evaluateGuardrails() output for this run's protocol.improvement.criticalGuardrails: [{key, threshold, value, status}]. guardrail_status is the reduced pass/fail/not_established this column explains.",
    },
  },
  eval_score: {
    columns: [
      [
        "eval_id",
        "uuid",
        false,
        null,
      ],
      [
        "subject_id",
        "uuid",
        false,
        null,
      ],
      [
        "dimension_id",
        "uuid",
        false,
        null,
      ],
      [
        "score",
        "numeric(2,1)",
        false,
        null,
      ],
      [
        "quote",
        "text",
        false,
        "''::text",
      ],
      [
        "reason",
        "text",
        false,
        "''::text",
      ],
      [
        "is_control",
        "boolean",
        false,
        "false",
      ],
      [
        "confidence",
        "numeric",
        true,
        null,
      ],
      [
        "probabilities",
        "jsonb",
        true,
        null,
      ],
    ],
    primaryKey: [
      "eval_id",
      "subject_id",
      "dimension_id",
      "is_control",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "dimension_id",
        ],
        refTable: "rubric_dimension",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "eval_id",
        ],
        refTable: "eval",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
      {
        columns: [
          "subject_id",
        ],
        refTable: "eval_subject",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK (((score >= (1)::numeric) AND (score <= (5)::numeric)))",
    ],
    indexes: [],
    comment: null,
    columnComments: {
      score: "One dimension, 1.0-5.0. Halves allowed: a judge who means 4.5 must not be recorded as 5.",
    },
  },
  eval_subject: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "eval_id",
        "uuid",
        false,
        null,
      ],
      [
        "team_id",
        "uuid",
        true,
        null,
      ],
      [
        "initiative_slug",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        true,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        "''::text",
      ],
      [
        "git_commit",
        "text",
        false,
        "''::text",
      ],
      [
        "doc_id",
        "uuid",
        true,
        null,
      ],
      [
        "evaluated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "run_id",
        "uuid",
        true,
        null,
      ],
      [
        "plugin_version_id",
        "uuid",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "eval_id",
        "initiative_slug",
        "path",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "eval_id",
        ],
        refTable: "eval",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
      {
        columns: [
          "plugin_version_id",
        ],
        refTable: "plugin_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "run_id",
        ],
        refTable: "run",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
      {
        columns: [
          "team_id",
        ],
        refTable: "team",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((((path IS NOT NULL) AND (run_id IS NULL)) OR ((path IS NULL) AND (run_id IS NOT NULL))))",
    ],
    indexes: [
      "CREATE INDEX eval_subject_doc ON zz.eval_subject USING btree (initiative_slug, path)",
    ],
    comment: null,
    columnComments: {
      run_id: "The window of work judged, when a skill produces no document. Exactly one of path/run_id.",
    },
  },
};
