/**
 * Generated by `scripts/schema-target-extract.ts` — part 2 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_2: Record<string, TableTarget> = {
  artifact_revision: {
    columns: [
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "revision",
        "integer",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        null,
      ],
      [
        "payload",
        "jsonb",
        false,
        null,
      ],
      [
        "cause_refs",
        "jsonb",
        false,
        "'[]'::jsonb",
      ],
      [
        "sources",
        "jsonb",
        false,
        "'[]'::jsonb",
      ],
      [
        "generated_by",
        "text",
        true,
        null,
      ],
      [
        "generated_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "origin_profile",
        "text",
        false,
        null,
      ],
      [
        "legacy_unresolved_sources",
        "jsonb",
        false,
        "'[]'::jsonb",
      ],
      [
        "previous_revision",
        "integer",
        true,
        null,
      ],
    ],
    primaryKey: [
      "owner_id",
      "artifact_id",
      "revision",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "owner_id",
          "artifact_id",
        ],
        refTable: "artifact",
        refColumns: [
          "owner_id",
          "artifact_id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((origin_profile = ANY (ARRAY['native'::text, 'legacy_import'::text])))",
      "CHECK (((previous_revision IS NULL) OR (previous_revision > 0)))",
      "CHECK ((revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  assessment: {
    columns: [
      [
        "id",
        "bigint",
        false,
        null,
      ],
      [
        "family",
        "text",
        true,
        null,
      ],
      [
        "instruction_version",
        "integer",
        false,
        null,
      ],
      [
        "question_digest",
        "text",
        false,
        null,
      ],
      [
        "reading",
        "text",
        true,
        null,
      ],
      [
        "probability",
        "numeric",
        true,
        null,
      ],
      [
        "requested_model",
        "text",
        true,
        null,
      ],
      [
        "resolved_model",
        "text",
        true,
        null,
      ],
      [
        "identity_assurance",
        "text",
        true,
        null,
      ],
      [
        "reason",
        "text",
        true,
        null,
      ],
      [
        "initiative",
        "text",
        true,
        null,
      ],
      [
        "about",
        "text",
        true,
        null,
      ],
      [
        "asked_by",
        "text",
        false,
        null,
      ],
      [
        "asked_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "evaluator_version_id",
        "uuid",
        true,
        null,
      ],
      [
        "distribution",
        "jsonb",
        true,
        null,
      ],
      [
        "answer_kind",
        "text",
        false,
        "'noul'::text",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "evaluator_version_id",
        ],
        refTable: "eval_evaluator_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((answer_kind = ANY (ARRAY['noul'::text, 'choice'::text, 'score'::text])))",
      "CHECK (((answer_kind <> ALL (ARRAY['choice'::text, 'score'::text])) OR (distribution IS NOT NULL) OR ((reading = 'unavailable'::text) AND (reason IS NOT NULL))))",
      "CHECK (((family IS NULL) OR ((reading IS NOT NULL) AND (answer_kind = 'noul'::text))))",
      "CHECK (((family IS NOT NULL) <> (evaluator_version_id IS NOT NULL)))",
      "CHECK ((reading = ANY (ARRAY['yes'::text, 'no'::text, 'unclear'::text, 'unavailable'::text])))",
    ],
    indexes: [
      "CREATE INDEX assessment_initiative_idx ON zz.assessment USING btree (initiative, asked_at)",
    ],
    comment: "Every semantic-assessment question the platform asked the typed service, with its provenance. A reading of unavailable carries its reason.",
    columnComments: {
      evaluator_version_id: "Set instead of family for a plugin-eval question. Exactly one of the two is non-null.",
      distribution: "The full answer distribution for a choice/score evaluator question. probability keeps carrying the noul probability.",
      answer_kind: "noul | choice | score — which typed-service primitive answered this question. Defaults to noul, so every row written before this migration reads as noul unchanged.",
    },
  },
  bug: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "reported_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "reported_by",
        "text",
        false,
        null,
      ],
      [
        "team_slug",
        "text",
        true,
        null,
      ],
      [
        "title",
        "text",
        false,
        null,
      ],
      [
        "detail",
        "text",
        false,
        null,
      ],
      [
        "surface",
        "text",
        true,
        null,
      ],
      [
        "initiative",
        "text",
        true,
        null,
      ],
      [
        "platform_version",
        "text",
        true,
        null,
      ],
      [
        "impact",
        "text",
        false,
        "'wrong_result'::text",
      ],
      [
        "status",
        "text",
        false,
        "'open'::text",
      ],
      [
        "resolution",
        "text",
        true,
        null,
      ],
      [
        "resolved_by",
        "text",
        true,
        null,
      ],
      [
        "resolved_at",
        "timestamp with time zone",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [
      "CHECK ((impact = ANY (ARRAY['blocks_work'::text, 'wrong_result'::text, 'confusing'::text, 'cosmetic'::text])))",
      "CHECK ((((status = 'open'::text) AND (resolution IS NULL) AND (resolved_by IS NULL) AND (resolved_at IS NULL)) OR ((status <> 'open'::text) AND (resolution IS NOT NULL) AND (resolved_by IS NOT NULL) AND (resolved_at IS NOT NULL))))",
      "CHECK ((status = ANY (ARRAY['open'::text, 'fixed'::text, 'not_a_bug'::text, 'duplicate'::text])))",
    ],
    indexes: [
      "CREATE INDEX bug_open ON zz.bug USING btree (status, reported_at DESC)",
      "CREATE INDEX bug_team ON zz.bug USING btree (team_slug, reported_at DESC)",
    ],
    comment: "Bugs reported by the people using this platform. Written by bug_report on /core, read by bug_list, closed by bug_resolve. Not knowledge (a report needs no evidence) and not an event (an event has no author).",
    columnComments: {},
  },
  candidate: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "improvement_run_id",
        "uuid",
        false,
        null,
      ],
      [
        "base_subject_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "hypothesis",
        "text",
        false,
        null,
      ],
      [
        "expected_effect",
        "jsonb",
        false,
        null,
      ],
      [
        "patchset",
        "jsonb",
        false,
        null,
      ],
      [
        "patch_digest",
        "text",
        false,
        null,
      ],
      [
        "complexity_delta",
        "integer",
        false,
        null,
      ],
      [
        "touched_components",
        "jsonb",
        false,
        null,
      ],
      [
        "touched_owners",
        "jsonb",
        false,
        null,
      ],
      [
        "proposer_identity",
        "jsonb",
        false,
        null,
      ],
      [
        "status",
        "text",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
      [
        "build_requested_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "build_requested_by",
        "text",
        true,
        null,
      ],
      [
        "build_result",
        "jsonb",
        true,
        null,
      ],
      [
        "build_recorded_at",
        "timestamp with time zone",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "base_subject_version_id",
        ],
        refTable: "eval_subject_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "improvement_run_id",
        ],
        refTable: "improvement_run",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((status = ANY (ARRAY['recorded'::text, 'awaiting_build'::text, 'valid'::text, 'invalid'::text, 'released'::text, 'rolled_back'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {
      status: "rolled_back: release_record set the same candidate's own release_attempt to rolled_back after packages/tools/src/release/rollback.ts restored the prior released version — set alongside it, in the same recordRelease transaction, never on its own.",
      build_result: "What npm run candidate-build recorded through candidate_build_record: {ok, stage, log_tail, commands, patch_digest}. Kept once candidate_validate consumes it, so improvement.md and the console can say how the released patch was built and gated.",
    },
  },
  console_session: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "principal_id",
        "uuid",
        false,
        null,
      ],
      [
        "token_hash",
        "text",
        false,
        null,
      ],
      [
        "issued_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "expires_at",
        "timestamp with time zone",
        false,
        null,
      ],
      [
        "revoked_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "last_seen_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "user_agent",
        "text",
        true,
        null,
      ],
      [
        "ip",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "token_hash",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX console_session_expiry ON zz.console_session USING btree (expires_at)",
      "CREATE INDEX console_session_principal ON zz.console_session USING btree (principal_id)",
    ],
    comment: null,
    columnComments: {},
  },
};
