/**
 * Generated by `scripts/schema-target-extract.ts` — part 9 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_9: Record<string, TableTarget> = {
  plugin: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "name",
        "text",
        false,
        null,
      ],
      [
        "origin",
        "text",
        false,
        null,
      ],
      [
        "owner_team",
        "text",
        true,
        null,
      ],
      [
        "evolvable",
        "boolean",
        false,
        "false",
      ],
      [
        "release_owners",
        "jsonb",
        false,
        "'[]'::jsonb",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "name",
      ],
    ],
    foreignKeys: [],
    checks: [
      "CHECK ((origin = ANY (ARRAY['platform'::text, 'third_party'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  plugin_tool: {
    columns: [
      [
        "plugin_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "name",
        "text",
        false,
        null,
      ],
      [
        "door",
        "text",
        false,
        null,
      ],
    ],
    primaryKey: [
      "plugin_version_id",
      "name",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "plugin_version_id",
        ],
        refTable: "plugin_version",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  plugin_version: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "plugin_id",
        "uuid",
        false,
        null,
      ],
      [
        "version",
        "text",
        false,
        null,
      ],
      [
        "digest",
        "text",
        false,
        null,
      ],
      [
        "rubric_id",
        "uuid",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "plugin_id",
        "version",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "plugin_id",
        ],
        refTable: "plugin",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "rubric_id",
        ],
        refTable: "rubric",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  plugin_version_skill: {
    columns: [
      [
        "plugin_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "skill_version_id",
        "uuid",
        false,
        null,
      ],
    ],
    primaryKey: [
      "plugin_version_id",
      "skill_version_id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "plugin_version_id",
        ],
        refTable: "plugin_version",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
      {
        columns: [
          "skill_version_id",
        ],
        refTable: "skill_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  principal: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "email",
        "zz.citext",
        false,
        null,
      ],
      [
        "display_name",
        "text",
        false,
        "''::text",
      ],
      [
        "role",
        "text",
        false,
        "'member'::text",
      ],
      [
        "status",
        "text",
        false,
        "'active'::text",
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "active_team_id",
        "uuid",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "email",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "active_team_id",
        ],
        refTable: "team",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((role = ANY (ARRAY['superadmin'::text, 'member'::text])))",
      "CHECK ((status = ANY (ARRAY['active'::text, 'deactivated'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  release_attempt: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "candidate_id",
        "uuid",
        false,
        null,
      ],
      [
        "base_subject_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "approved_patch_digest",
        "text",
        false,
        null,
      ],
      [
        "required_owners",
        "jsonb",
        false,
        null,
      ],
      [
        "approval_refs",
        "jsonb",
        false,
        null,
      ],
      [
        "status",
        "text",
        false,
        null,
      ],
      [
        "released_subject_version_id",
        "uuid",
        true,
        null,
      ],
      [
        "release_ref",
        "text",
        true,
        null,
      ],
      [
        "verification",
        "jsonb",
        true,
        null,
      ],
      [
        "rolled_back",
        "boolean",
        false,
        "false",
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
      [
        "reason",
        "text",
        true,
        null,
      ],
      [
        "plugin_id",
        "uuid",
        false,
        null,
      ],
      [
        "applied_by",
        "text",
        true,
        null,
      ],
      [
        "applying_at",
        "timestamp with time zone",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "base_subject_version_id",
        ],
        refTable: "eval_subject_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "candidate_id",
        ],
        refTable: "candidate",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "plugin_id",
        ],
        refTable: "plugin",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "released_subject_version_id",
        ],
        refTable: "eval_subject_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((status = ANY (ARRAY['prepared'::text, 'applying'::text, 'released'::text, 'refused'::text, 'failed'::text, 'rolled_back'::text])))",
    ],
    indexes: [
      "CREATE UNIQUE INDEX release_attempt_applying_plugin_idx ON zz.release_attempt USING btree (plugin_id) WHERE (status = 'applying'::text)",
      "CREATE UNIQUE INDEX release_attempt_live_candidate_idx ON zz.release_attempt USING btree (candidate_id) WHERE (status = ANY (ARRAY['applying'::text, 'released'::text]))",
    ],
    comment: null,
    columnComments: {
      verification: "release_verify's decision, once it has one: {verdict (established | rolled_back | not_established), reason, evidence: {post_release_runs, released_eval_run_id, released_overall, base_eval_run_id, base_overall, delta, regression_band, guardrail_status}, rollback_plan}. Null until the released subject has enough real runs and an evaluation to judge.",
      reason: "Why this attempt ended as it did: releaseDecision's own reason on a refusal, the failing command's output tail (release_record) on a failure, the operator's reason on a rollback, or the accepted override (--reconcile --accept-tag-without-candidate-commit) on a reconciled release. Null for prepared/applying, and for a release proved without an override.",
      plugin_id: "The plugin this attempt releases — the base subject's own plugin, written by release_prepare. Keys release_attempt_applying_plugin_idx: at most one applying attempt per plugin.",
      applied_by: "The principal whose release_apply moved this attempt to applying. release_record and release_verify accept that principal or a member of a required owner team, nobody else.",
      applying_at: "When release_apply moved this attempt to applying. An attempt still applying long after the CLI's own gate and release timeouts is stale: release_apply names it for reconciliation.",
    },
  },
  rubric: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "version",
        "text",
        false,
        null,
      ],
      [
        "derived_from_eval",
        "uuid",
        true,
        null,
      ],
      [
        "approved_by",
        "text",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "subject",
        "text",
        false,
        "'auto'::text",
      ],
      [
        "plugin_id",
        "uuid",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "plugin_id",
        ],
        refTable: "plugin",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((subject = ANY (ARRAY['auto'::text, 'document'::text, 'trace'::text, 'initiative'::text])))",
    ],
    indexes: [
      "CREATE UNIQUE INDEX rubric_plugin_id_version_key ON zz.rubric USING btree (plugin_id, version)",
    ],
    comment: null,
    columnComments: {
      subject: "What this ruler is applied to: the documents the subject produced, its run traces, or auto — documents where they exist and traces otherwise.",
    },
  },
  rubric_dimension: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "rubric_id",
        "uuid",
        false,
        null,
      ],
      [
        "name",
        "text",
        false,
        null,
      ],
      [
        "five_means",
        "text",
        false,
        null,
      ],
      [
        "one_means",
        "text",
        false,
        null,
      ],
      [
        "ordinal",
        "integer",
        false,
        "0",
      ],
      [
        "kind",
        "text",
        false,
        "'qualitative'::text",
      ],
      [
        "threshold",
        "text",
        false,
        "''::text",
      ],
      [
        "threshold_reason",
        "text",
        false,
        "''::text",
      ],
      [
        "levels",
        "text[]",
        true,
        null,
      ],
      [
        "reads",
        "text[]",
        false,
        "'{}'::text[]",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "rubric_id",
        "name",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "rubric_id",
        ],
        refTable: "rubric",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((kind = ANY (ARRAY['qualitative'::text, 'quantitative'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {
      reads: "Dotted paths into the facts sheet plugin_profile produces, e.g. record.revised_with_evidence_pct. Empty for a qualitative dimension, which reads the artifact instead. A quantitative dimension whose paths are not on the sheet cannot be measured, and is refused at ruler_record.",
    },
  },
};
