/**
 * Generated by `scripts/schema-target-extract.ts` — part 3 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_3: Record<string, TableTarget> = {
  control_evidence: {
    columns: [
      [
        "seq",
        "bigint",
        false,
        "nextval('zz.control_evidence_seq_seq'::regclass)",
      ],
      [
        "run_id",
        "uuid",
        false,
        null,
      ],
      [
        "entry_id",
        "text",
        false,
        null,
      ],
      [
        "step_id",
        "text",
        false,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
      [
        "about",
        "text",
        false,
        null,
      ],
      [
        "note",
        "text",
        false,
        "''::text",
      ],
      [
        "recorded_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "recorded_by",
        "text",
        true,
        null,
      ],
      [
        "supersedes",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "seq",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "run_id",
        ],
        refTable: "control_run",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX control_evidence_run_seq ON zz.control_evidence USING btree (run_id, seq)",
      "CREATE INDEX control_evidence_supersedes ON zz.control_evidence USING btree (run_id, supersedes) WHERE (supersedes IS NOT NULL)",
    ],
    comment: null,
    columnComments: {},
  },
  control_run: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "initiative",
        "text",
        false,
        null,
      ],
      [
        "module_id",
        "text",
        false,
        null,
      ],
      [
        "module_digest",
        "text",
        false,
        null,
      ],
      [
        "subject",
        "text",
        false,
        null,
      ],
      [
        "profile",
        "jsonb",
        false,
        "'[]'::jsonb",
      ],
      [
        "started_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "started_by",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "team_slug",
        "initiative",
      ],
    ],
    foreignKeys: [],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  control_waiver: {
    columns: [
      [
        "seq",
        "bigint",
        false,
        "nextval('zz.control_waiver_seq_seq'::regclass)",
      ],
      [
        "run_id",
        "uuid",
        false,
        null,
      ],
      [
        "step_id",
        "text",
        false,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
      [
        "ground",
        "text",
        false,
        null,
      ],
      [
        "recorded_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "recorded_by",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "seq",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "run_id",
        ],
        refTable: "control_run",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX control_waiver_run ON zz.control_waiver USING btree (run_id)",
    ],
    comment: null,
    columnComments: {},
  },
  decision: {
    columns: [
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "initiative",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "role",
        "text",
        false,
        null,
      ],
      [
        "key",
        "text",
        false,
        null,
      ],
      [
        "verdict",
        "text",
        false,
        "''::text",
      ],
      [
        "qualifier",
        "text",
        false,
        "''::text",
      ],
      [
        "detail",
        "text",
        false,
        "''::text",
      ],
      [
        "checker",
        "text",
        false,
        "''::text",
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "doc_id",
        "uuid",
        true,
        null,
      ],
    ],
    primaryKey: [
      "team_slug",
      "initiative",
      "path",
      "key",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "doc_id",
        ],
        refTable: "doc",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((verdict = ANY (ARRAY[''::text, 'native'::text, 'achievable'::text, 'workaround'::text, 'not_possible'::text])))",
    ],
    indexes: [
      "CREATE INDEX decision_team_initiative ON zz.decision USING btree (team_slug, initiative)",
    ],
    comment: null,
    columnComments: {},
  },
  discussion_message: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "initiative",
        "text",
        false,
        null,
      ],
      [
        "doc_path",
        "text",
        false,
        null,
      ],
      [
        "seq",
        "integer",
        false,
        null,
      ],
      [
        "principal_id",
        "uuid",
        false,
        null,
      ],
      [
        "body",
        "text",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "team_slug",
        "initiative",
        "doc_path",
        "seq",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX discussion_thread ON zz.discussion_message USING btree (team_slug, initiative, doc_path, seq)",
    ],
    comment: null,
    columnComments: {},
  },
  doc: {
    columns: [
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "initiative",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "flow",
        "text",
        false,
        "''::text",
      ],
      [
        "type",
        "text",
        false,
        "''::text",
      ],
      [
        "status",
        "text",
        false,
        "''::text",
      ],
      [
        "outcome",
        "text",
        true,
        null,
      ],
      [
        "approved_by",
        "text",
        true,
        null,
      ],
      [
        "approved_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        null,
      ],
      [
        "body_tsv",
        "tsvector",
        true,
        null,
      ],
      [
        "body",
        "text",
        false,
        "''::text",
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "evidence",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "superseded_by",
        "text",
        true,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        "''::text",
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "closed_by",
        "text",
        true,
        null,
      ],
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "initiative_id",
        "uuid",
        true,
        null,
      ],
      [
        "produced_by_run_id",
        "uuid",
        true,
        null,
      ],
      [
        "supports",
        "text",
        true,
        null,
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "team_slug",
      "initiative",
      "path",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "initiative_id",
        ],
        refTable: "initiative",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
      {
        columns: [
          "produced_by_run_id",
        ],
        refTable: "run",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK (((outcome IS NULL) OR (outcome = ANY (ARRAY['delivered'::text, 'accepted'::text, 'abandoned'::text]))))",
      "CHECK ((status = ANY (ARRAY[''::text, 'draft'::text, 'approved'::text, 'adopted'::text, 'superseded'::text])))",
    ],
    indexes: [
      "CREATE INDEX doc_evidence ON zz.doc USING gin (evidence)",
      "CREATE INDEX doc_supports ON zz.doc USING btree (team_slug, initiative, supports) WHERE (supports IS NOT NULL)",
      "CREATE INDEX doc_tags ON zz.doc USING gin (tags)",
      "CREATE INDEX doc_team_type ON zz.doc USING btree (team_slug, type, status)",
      "CREATE INDEX doc_tsv ON zz.doc USING gin (body_tsv)",
    ],
    comment: null,
    columnComments: {
      approved_by: "The one signature field. A person, never a team slug, \"the user\" or \"the agent\" — and\n   stamped by approve() / close() from the session, never typed by a model.",
      created_at: "When this document first existed. Never moves. `updated_at` is the last write; this is the\n   first, and it is what scopes a measurement to one initiative's lifetime.",
    },
  },
};
