/**
 * Generated by `scripts/schema-target-extract.ts` — part 8 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_8: Record<string, TableTarget> = {
  mcp_oauth_authz: {
    columns: [
      [
        "id",
        "text",
        false,
        null,
      ],
      [
        "client_id",
        "text",
        false,
        null,
      ],
      [
        "principal_id",
        "uuid",
        true,
        null,
      ],
      [
        "redirect_uri",
        "text",
        false,
        null,
      ],
      [
        "code_challenge",
        "text",
        false,
        null,
      ],
      [
        "state",
        "text",
        false,
        "''::text",
      ],
      [
        "resource",
        "text",
        false,
        "''::text",
      ],
      [
        "used",
        "boolean",
        false,
        "false",
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX mcp_oauth_authz_age ON zz.mcp_oauth_authz USING btree (created_at)",
    ],
    comment: null,
    columnComments: {},
  },
  mcp_oauth_client: {
    columns: [
      [
        "client_id",
        "text",
        false,
        null,
      ],
      [
        "redirect_uris",
        "jsonb",
        false,
        null,
      ],
      [
        "name",
        "text",
        false,
        "''::text",
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "client_id",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  membership: {
    columns: [
      [
        "team_id",
        "uuid",
        false,
        null,
      ],
      [
        "principal_id",
        "uuid",
        false,
        null,
      ],
      [
        "role",
        "text",
        false,
        "'member'::text",
      ],
      [
        "added_by",
        "uuid",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "team_id",
      "principal_id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "added_by",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "team_id",
        ],
        refTable: "team",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((role = ANY (ARRAY['admin'::text, 'member'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  model_call: {
    columns: [
      [
        "id",
        "bigint",
        false,
        null,
      ],
      [
        "ts",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "event_id",
        "bigint",
        true,
        null,
      ],
      [
        "plugin",
        "text",
        true,
        null,
      ],
      [
        "purpose",
        "text",
        false,
        null,
      ],
      [
        "model",
        "text",
        false,
        null,
      ],
      [
        "input_tokens",
        "integer",
        true,
        null,
      ],
      [
        "output_tokens",
        "integer",
        true,
        null,
      ],
      [
        "cache_read_tokens",
        "integer",
        true,
        null,
      ],
      [
        "duration_ms",
        "integer",
        true,
        null,
      ],
      [
        "ok",
        "boolean",
        false,
        null,
      ],
      [
        "attempts",
        "integer",
        false,
        "1",
      ],
      [
        "confidence",
        "numeric",
        true,
        null,
      ],
      [
        "note",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "event_id",
        ],
        refTable: "event",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX model_call_failed_ts ON zz.model_call USING btree (ts DESC) WHERE (NOT ok)",
      "CREATE INDEX model_call_plugin_ts ON zz.model_call USING btree (plugin, ts)",
      "CREATE INDEX model_call_purpose_ts ON zz.model_call USING btree (purpose, ts)",
    ],
    comment: null,
    columnComments: {},
  },
  passkey: {
    columns: [
      [
        "id",
        "text",
        false,
        null,
      ],
      [
        "principal_id",
        "uuid",
        false,
        null,
      ],
      [
        "public_key",
        "bytea",
        false,
        null,
      ],
      [
        "counter",
        "bigint",
        false,
        "0",
      ],
      [
        "transports",
        "text[]",
        true,
        null,
      ],
      [
        "label",
        "text",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "last_used_at",
        "timestamp with time zone",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX passkey_principal ON zz.passkey USING btree (principal_id)",
    ],
    comment: null,
    columnComments: {},
  },
  passkey_challenge: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "challenge",
        "text",
        false,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
      [
        "principal_id",
        "uuid",
        true,
        null,
      ],
      [
        "redirect_to",
        "text",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((kind = ANY (ARRAY['register'::text, 'login'::text])))",
    ],
    indexes: [
      "CREATE INDEX passkey_challenge_age ON zz.passkey_challenge USING btree (created_at)",
    ],
    comment: null,
    columnComments: {},
  },
  passkey_enrolment: {
    columns: [
      [
        "token_hash",
        "text",
        false,
        null,
      ],
      [
        "principal_id",
        "uuid",
        false,
        null,
      ],
      [
        "issued_by",
        "uuid",
        true,
        null,
      ],
      [
        "expires_at",
        "timestamp with time zone",
        false,
        null,
      ],
      [
        "used_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "token_hash",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "issued_by",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX passkey_enrolment_expiry ON zz.passkey_enrolment USING btree (expires_at)",
      "CREATE INDEX passkey_enrolment_principal ON zz.passkey_enrolment USING btree (principal_id)",
    ],
    comment: null,
    columnComments: {},
  },
  pat: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "principal_id",
        "uuid",
        false,
        null,
      ],
      [
        "token_hash",
        "text",
        false,
        null,
      ],
      [
        "label",
        "text",
        false,
        "''::text",
      ],
      [
        "team_id",
        "uuid",
        true,
        null,
      ],
      [
        "expires_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "revoked_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "last_used_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "token_hash",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "principal_id",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "team_id",
        ],
        refTable: "team",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
};
