/**
 * Generated by `scripts/schema-target-extract.ts` — part 7 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_7: Record<string, TableTarget> = {
  eval_subject_version: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "plugin_id",
        "uuid",
        false,
        null,
      ],
      [
        "declared_version",
        "text",
        false,
        null,
      ],
      [
        "content_digest",
        "text",
        false,
        null,
      ],
      [
        "component_manifest",
        "jsonb",
        false,
        null,
      ],
      [
        "source_locator",
        "jsonb",
        false,
        null,
      ],
      [
        "release_identity",
        "jsonb",
        false,
        null,
      ],
      [
        "captured_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "plugin_id",
        "declared_version",
        "content_digest",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "plugin_id",
        ],
        refTable: "plugin",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  event: {
    columns: [
      [
        "id",
        "bigint",
        false,
        null,
      ],
      [
        "ts",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "actor",
        "text",
        false,
        null,
      ],
      [
        "team_slug",
        "text",
        true,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
      [
        "subject",
        "text",
        false,
        "''::text",
      ],
      [
        "detail",
        "jsonb",
        false,
        "'{}'::jsonb",
      ],
      [
        "initiative",
        "text",
        true,
        null,
      ],
      [
        "flow",
        "text",
        true,
        null,
      ],
      [
        "step",
        "text",
        true,
        null,
      ],
      [
        "step_version",
        "text",
        true,
        null,
      ],
      [
        "ok",
        "boolean",
        true,
        null,
      ],
      [
        "refusal",
        "text",
        true,
        null,
      ],
      [
        "run_id",
        "uuid",
        true,
        null,
      ],
      [
        "team_id",
        "uuid",
        true,
        null,
      ],
      [
        "duration_ms",
        "integer",
        true,
        null,
      ],
      [
        "request_bytes",
        "integer",
        true,
        null,
      ],
      [
        "response_bytes",
        "integer",
        true,
        null,
      ],
      [
        "batched",
        "boolean",
        false,
        "false",
      ],
      [
        "plugin",
        "text",
        true,
        null,
      ],
      [
        "plugin_version",
        "text",
        true,
        null,
      ],
      [
        "tool_key",
        "text",
        true,
        null,
      ],
      [
        "refusal_owner",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "run_id",
        ],
        refTable: "run",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
      {
        columns: [
          "team_id",
        ],
        refTable: "team",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX event_initiative ON zz.event USING btree (team_slug, initiative) WHERE (initiative IS NOT NULL)",
      "CREATE INDEX event_kind_ts ON zz.event USING btree (kind, ts)",
      "CREATE INDEX event_refusal_owner_idx ON zz.event USING btree (refusal_owner) WHERE (ok = false)",
      "CREATE INDEX event_run ON zz.event USING btree (run_id) WHERE (run_id IS NOT NULL)",
      "CREATE INDEX event_step ON zz.event USING btree (step, step_version) WHERE (step IS NOT NULL)",
      "CREATE INDEX event_team_ts ON zz.event USING btree (team_slug, ts)",
    ],
    comment: null,
    columnComments: {
      initiative: "Join key to zz.doc and zz.decision. Carried forward per caller from the last call that named\n   one, because most calls do not take it as an argument.",
      flow: "The flow the call's initiative runs, as declared at initiative_open; empty for a call made outside any initiative. Not attribution: use plugin / plugin_version for which plugin owns this call.",
      step: "The skill this call was following, or NULL when none was. Never the empty string: `??` does not coalesce it, so an empty step reaches this column verbatim and is unjoinable to zz.skill while still looking like a value. Producers say unknown by omitting the field.",
      step_version: "The version declared by the skill that was served WHOLE, or NULL. A supporting file beside a skill carries no version, and that is recorded as NULL rather than as an empty string, for the same reason as step.",
      ok: "Whether the call worked, in the platform's own terms — never a transport status. An MCP\n   tool that refuses answers HTTP 200 with ERROR: in its text.",
      plugin: "Which plugin owns the skill the caller had loaded, resolved through zz.plugin_version_skill from currentStep() — never from flow_install and never from the x-zz-client header. Null when no skill was loaded, or the step names none that a plugin has released.",
      plugin_version: "The released version of `plugin` that shipped the skill version the caller was on. Null exactly when plugin is null.",
      tool_key: "The alias-resolved `<surface>:<tool>` name (Task I-2's resolver), so a row written after this column existed already reads as one series across a rename with no further lookup.",
    },
  },
  improvement_run: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "eval_run_id",
        "uuid",
        false,
        null,
      ],
      [
        "finding_ids",
        "jsonb",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "eval_run_id",
        ],
        refTable: "eval_run",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  initiative: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "team_id",
        "uuid",
        false,
        null,
      ],
      [
        "slug",
        "text",
        false,
        null,
      ],
      [
        "flow",
        "text",
        false,
        "''::text",
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "team_id",
        "slug",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "team_id",
        ],
        refTable: "team",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  initiative_fact: {
    columns: [
      [
        "id",
        "bigint",
        false,
        null,
      ],
      [
        "team",
        "text",
        false,
        null,
      ],
      [
        "initiative",
        "text",
        false,
        null,
      ],
      [
        "fact",
        "text",
        false,
        null,
      ],
      [
        "value",
        "text",
        false,
        null,
      ],
      [
        "set_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "team",
        "initiative",
        "fact",
      ],
    ],
    foreignKeys: [],
    checks: [],
    indexes: [
      "CREATE INDEX initiative_fact_lookup_idx ON zz.initiative_fact USING btree (team, initiative)",
    ],
    comment: "Mirror of <initiative>/_facts.json for the console. The file is authoritative; a row here is never updated once written for a given (team, initiative, fact).",
    columnComments: {},
  },
  knowledge_node: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
      [
        "lifecycle",
        "text",
        false,
        "'adopted'::text",
      ],
      [
        "superseded_by",
        "text",
        true,
        null,
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "body",
        "text",
        false,
        "''::text",
      ],
      [
        "body_tsv",
        "tsvector",
        true,
        null,
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "evidence",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "content_hash",
        "text",
        false,
        "''::text",
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "team_slug",
        "path",
      ],
    ],
    foreignKeys: [],
    checks: [
      "CHECK ((kind = ANY (ARRAY['decision'::text, 'design'::text, 'process'::text, 'knowledge'::text, 'behavior'::text, 'style'::text])))",
      "CHECK ((lifecycle = ANY (ARRAY['adopted'::text, 'superseded'::text])))",
    ],
    indexes: [
      "CREATE INDEX knowledge_node_tags ON zz.knowledge_node USING gin (tags)",
      "CREATE INDEX knowledge_node_team ON zz.knowledge_node USING btree (team_slug, lifecycle)",
      "CREATE INDEX knowledge_node_tsv ON zz.knowledge_node USING gin (body_tsv)",
    ],
    comment: null,
    columnComments: {},
  },
  knowledge_node_artifact: {
    columns: [
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "current_revision",
        "integer",
        false,
        null,
      ],
      [
        "origin_profile",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "team_slug",
      "path",
    ],
    uniques: [
      [
        "owner_id",
        "artifact_id",
      ],
    ],
    foreignKeys: [],
    checks: [
      "CHECK ((current_revision > 0))",
      "CHECK ((origin_profile = ANY (ARRAY['native'::text, 'legacy_import'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
};
