/**
 * Generated by `scripts/schema-target-extract.ts` — part 11 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_11: Record<string, TableTarget> = {
  team: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "slug",
        "text",
        false,
        null,
      ],
      [
        "name",
        "text",
        false,
        null,
      ],
      [
        "status",
        "text",
        false,
        "'active'::text",
      ],
      [
        "created_by",
        "uuid",
        false,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "slug",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "created_by",
        ],
        refTable: "principal",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((status = ANY (ARRAY['active'::text, 'archived'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
};
