/**
 * Generated by `scripts/schema-target-extract.ts` — part 4 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_4: Record<string, TableTarget> = {
  doc_artifact: {
    columns: [
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "initiative",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "current_revision",
        "integer",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "team_slug",
      "initiative",
      "path",
    ],
    uniques: [
      [
        "owner_id",
        "artifact_id",
      ],
    ],
    foreignKeys: [],
    checks: [
      "CHECK ((current_revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "rubric_id",
        "uuid",
        false,
        null,
      ],
      [
        "judge_model",
        "text",
        false,
        "''::text",
      ],
      [
        "selection_note",
        "text",
        false,
        "''::text",
      ],
      [
        "doc_count",
        "integer",
        false,
        "0",
      ],
      [
        "started_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "finished_at",
        "timestamp with time zone",
        true,
        null,
      ],
      [
        "is_control",
        "boolean",
        false,
        "false",
      ],
      [
        "plugin_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "controls",
        "uuid",
        true,
        null,
      ],
      [
        "initiative",
        "text",
        true,
        null,
      ],
      [
        "team_slug",
        "text",
        true,
        null,
      ],
      [
        "effectiveness",
        "numeric",
        true,
        null,
      ],
      [
        "headroom_points",
        "numeric",
        true,
        null,
      ],
      [
        "headroom_named",
        "integer",
        true,
        null,
      ],
      [
        "headroom_state",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "controls",
        ],
        refTable: "eval",
        refColumns: [
          "id",
        ],
        onDelete: "SET NULL",
        deferrable: false,
      },
      {
        columns: [
          "plugin_version_id",
        ],
        refTable: "plugin_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "rubric_id",
        ],
        refTable: "rubric",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE INDEX eval_controls_idx ON zz.eval USING btree (controls) WHERE (controls IS NOT NULL)",
      "CREATE INDEX eval_latest_for_plugin_idx ON zz.eval USING btree (plugin_version_id, started_at DESC) WHERE ((NOT is_control) AND (headroom_state IS NOT NULL))",
    ],
    comment: null,
    columnComments: {
      initiative: "The initiative this round was run inside — stamped by round_judge from its caller, never inferred from a name or a date. Null on rounds taken before migration 067.",
      effectiveness: "0-10, as judge-score.ts computed it at round_recommend. Null when the round was void (a collapsed control), and null on rounds taken before migration 067.",
      headroom_state: "One of: no change needed, change identified, unexplained gap, not measured. The second axis. It reports what the evidence says about the gap and prescribes nothing — whether a change CAN be made is not something a score establishes.",
    },
  },
  eval_assessment: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "eval_run_id",
        "uuid",
        false,
        null,
      ],
      [
        "measure_id",
        "uuid",
        false,
        null,
      ],
      [
        "evaluator_version_id",
        "uuid",
        true,
        null,
      ],
      [
        "assessment_id",
        "bigint",
        true,
        null,
      ],
      [
        "qualification_id",
        "uuid",
        true,
        null,
      ],
      [
        "subject_ref",
        "text",
        false,
        null,
      ],
      [
        "evidence_ref",
        "text",
        false,
        null,
      ],
      [
        "answer",
        "jsonb",
        false,
        null,
      ],
      [
        "policy_version",
        "text",
        false,
        null,
      ],
      [
        "resulting_action",
        "text",
        true,
        null,
      ],
      [
        "created_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "assessment_id",
        ],
        refTable: "assessment",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "eval_run_id",
        ],
        refTable: "eval_run",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "evaluator_version_id",
        ],
        refTable: "eval_evaluator_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "measure_id",
        ],
        refTable: "eval_measure",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "qualification_id",
        ],
        refTable: "eval_evaluator_qualification",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_dimension: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "protocol_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "key",
        "text",
        false,
        null,
      ],
      [
        "name",
        "text",
        false,
        null,
      ],
      [
        "canonical_kind",
        "text",
        false,
        null,
      ],
      [
        "weight",
        "numeric",
        false,
        null,
      ],
      [
        "required",
        "boolean",
        false,
        null,
      ],
      [
        "applicable",
        "boolean",
        false,
        "true",
      ],
      [
        "not_applicable_reason",
        "text",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "protocol_version_id",
        ],
        refTable: "eval_protocol_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((canonical_kind = ANY (ARRAY['effectiveness'::text, 'reliability'::text, 'constraint_adherence'::text, 'recovery_robustness'::text, 'efficiency'::text, 'generalization'::text])))",
      "CHECK (((applicable AND (not_applicable_reason IS NULL)) OR ((NOT applicable) AND (not_applicable_reason IS NOT NULL))))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_evaluator: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "stable_key",
        "text",
        false,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "stable_key",
      ],
    ],
    foreignKeys: [],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_evaluator_qualification: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "evaluator_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "protocol_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "subject_scope",
        "jsonb",
        false,
        null,
      ],
      [
        "state",
        "text",
        false,
        null,
      ],
      [
        "evidence",
        "jsonb",
        false,
        null,
      ],
      [
        "qualified_at",
        "timestamp with time zone",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [],
    foreignKeys: [
      {
        columns: [
          "evaluator_version_id",
        ],
        refTable: "eval_evaluator_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
      {
        columns: [
          "protocol_version_id",
        ],
        refTable: "eval_protocol_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((state = ANY (ARRAY['unqualified'::text, 'mechanically_qualified'::text, 'operationally_qualified'::text, 'human_calibrated'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  eval_evaluator_version: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "evaluator_id",
        "uuid",
        false,
        null,
      ],
      [
        "version",
        "integer",
        false,
        null,
      ],
      [
        "question",
        "text",
        false,
        null,
      ],
      [
        "answer_schema",
        "jsonb",
        false,
        null,
      ],
      [
        "polarity",
        "jsonb",
        false,
        null,
      ],
      [
        "model_policy",
        "jsonb",
        false,
        null,
      ],
      [
        "content_digest",
        "text",
        false,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "evaluator_id",
        "version",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "evaluator_id",
        ],
        refTable: "eval_evaluator",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {},
  },
};
