/**
 * Generated by `scripts/schema-target-extract.ts` — part 10 of 11 of the
 * baseline catalog. Do not edit by hand; regenerate with the extractor.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const TABLES_10: Record<string, TableTarget> = {
  run: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "initiative_id",
        "uuid",
        true,
        null,
      ],
      [
        "skill_version_id",
        "uuid",
        true,
        null,
      ],
      [
        "caller_session",
        "text",
        false,
        "''::text",
      ],
      [
        "turns",
        "integer",
        false,
        "0",
      ],
      [
        "calls",
        "integer",
        false,
        "0",
      ],
      [
        "refusals",
        "integer",
        false,
        "0",
      ],
      [
        "bytes_total",
        "bigint",
        true,
        null,
      ],
      [
        "started_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "ended_at",
        "timestamp with time zone",
        true,
        null,
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "initiative_id",
        "skill_version_id",
        "caller_session",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "initiative_id",
        ],
        refTable: "initiative",
        refColumns: [
          "id",
        ],
        onDelete: "CASCADE",
        deferrable: false,
      },
      {
        columns: [
          "skill_version_id",
        ],
        refTable: "skill_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [
      "CREATE UNIQUE INDEX run_no_initiative ON zz.run USING btree (skill_version_id, caller_session) WHERE (initiative_id IS NULL)",
      "CREATE INDEX run_skill_version ON zz.run USING btree (skill_version_id, started_at DESC)",
    ],
    comment: null,
    columnComments: {
      bytes_total: "Sum of response_bytes over the run's events. Null when no event in the run was measured — distinct from 0, which means measured and empty. Zeros written before migration 051 are ambiguous and were deliberately not converted.",
    },
  },
  search_current: {
    columns: [
      [
        "corpus_key",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "revision",
        "integer",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        null,
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "type",
        "text",
        false,
        "''::text",
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "path",
        "text",
        false,
        "''::text",
      ],
      [
        "gate_status",
        "text",
        true,
        null,
      ],
      [
        "knowledge_status",
        "text",
        true,
        null,
      ],
      [
        "raw_body",
        "text",
        false,
        "''::text",
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
      [
        "projection_hash",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "corpus_key",
      "owner_id",
      "artifact_id",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [
      "CHECK ((revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  search_evidence: {
    columns: [
      [
        "corpus_key",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "revision",
        "integer",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        null,
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "type",
        "text",
        false,
        "''::text",
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "path",
        "text",
        false,
        "''::text",
      ],
      [
        "gate_status",
        "text",
        true,
        null,
      ],
      [
        "knowledge_status",
        "text",
        true,
        null,
      ],
      [
        "raw_body",
        "text",
        false,
        "''::text",
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
      [
        "projection_hash",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "corpus_key",
      "owner_id",
      "artifact_id",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [
      "CHECK ((revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  search_history: {
    columns: [
      [
        "corpus_key",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "revision",
        "integer",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        null,
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "type",
        "text",
        false,
        "''::text",
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "path",
        "text",
        false,
        "''::text",
      ],
      [
        "gate_status",
        "text",
        true,
        null,
      ],
      [
        "knowledge_status",
        "text",
        true,
        null,
      ],
      [
        "raw_body",
        "text",
        false,
        "''::text",
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
      [
        "projection_hash",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "corpus_key",
      "owner_id",
      "artifact_id",
      "revision",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [
      "CHECK ((revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  skill: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "name",
        "text",
        false,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
      [
        "flow",
        "text",
        true,
        null,
      ],
      [
        "ordinal",
        "integer",
        true,
        null,
      ],
      [
        "retired",
        "boolean",
        false,
        "false",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "name",
      ],
    ],
    foreignKeys: [],
    checks: [
      "CHECK ((((kind = 'flow_step'::text) AND (flow IS NOT NULL)) OR ((kind = 'plugin_skill'::text) AND (flow IS NULL))))",
    ],
    indexes: [],
    comment: null,
    columnComments: {
      retired: "No longer in the catalog. Kept because zz.run and zz.doc attribute documents to its versions.",
    },
  },
  skill_asset: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "skill_version_id",
        "uuid",
        false,
        null,
      ],
      [
        "kind",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        "''::text",
      ],
      [
        "description",
        "text",
        false,
        "''::text",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "skill_version_id",
        "path",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "skill_version_id",
        ],
        refTable: "skill_version",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [
      "CHECK ((kind = ANY (ARRAY['script'::text, 'reference'::text, 'tool_index'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  skill_version: {
    columns: [
      [
        "id",
        "uuid",
        false,
        "gen_random_uuid()",
      ],
      [
        "skill_id",
        "uuid",
        false,
        null,
      ],
      [
        "version",
        "text",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        "''::text",
      ],
      [
        "released_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
      [
        "body_hash",
        "text",
        false,
        "''::text",
      ],
    ],
    primaryKey: [
      "id",
    ],
    uniques: [
      [
        "skill_id",
        "version",
      ],
    ],
    foreignKeys: [
      {
        columns: [
          "skill_id",
        ],
        refTable: "skill",
        refColumns: [
          "id",
        ],
        onDelete: "NO ACTION",
        deferrable: false,
      },
    ],
    checks: [],
    indexes: [],
    comment: null,
    columnComments: {
      body_hash: "sha256 of the SKILL.md below its frontmatter. Equal hashes mean the skill itself did not change.",
    },
  },
};
