/**
 * The search shelves and the artifact bridges of documents and knowledge nodes.
 */
import type { TableTarget } from "../scripts/schema/types.ts";

export const SEARCH: Record<string, TableTarget> = {
  doc_artifact: {
    columns: [
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "initiative",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "current_revision",
        "integer",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "team_slug",
      "initiative",
      "path",
    ],
    uniques: [
      [
        "owner_id",
        "artifact_id",
      ],
    ],
    foreignKeys: [],
    checks: [
      "CHECK ((current_revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  knowledge_node_artifact: {
    columns: [
      [
        "team_slug",
        "text",
        false,
        null,
      ],
      [
        "path",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "current_revision",
        "integer",
        false,
        null,
      ],
      [
        "origin_profile",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "team_slug",
      "path",
    ],
    uniques: [
      [
        "owner_id",
        "artifact_id",
      ],
    ],
    foreignKeys: [],
    checks: [
      "CHECK ((current_revision > 0))",
      "CHECK ((origin_profile = ANY (ARRAY['native'::text, 'legacy_import'::text])))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  search_current: {
    columns: [
      [
        "corpus_key",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "revision",
        "integer",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        null,
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "type",
        "text",
        false,
        "''::text",
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "path",
        "text",
        false,
        "''::text",
      ],
      [
        "gate_status",
        "text",
        true,
        null,
      ],
      [
        "knowledge_status",
        "text",
        true,
        null,
      ],
      [
        "raw_body",
        "text",
        false,
        "''::text",
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
      [
        "projection_hash",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "corpus_key",
      "owner_id",
      "artifact_id",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [
      "CHECK ((revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  search_evidence: {
    columns: [
      [
        "corpus_key",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "revision",
        "integer",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        null,
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "type",
        "text",
        false,
        "''::text",
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "path",
        "text",
        false,
        "''::text",
      ],
      [
        "gate_status",
        "text",
        true,
        null,
      ],
      [
        "knowledge_status",
        "text",
        true,
        null,
      ],
      [
        "raw_body",
        "text",
        false,
        "''::text",
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
      [
        "projection_hash",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "corpus_key",
      "owner_id",
      "artifact_id",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [
      "CHECK ((revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
  search_history: {
    columns: [
      [
        "corpus_key",
        "text",
        false,
        null,
      ],
      [
        "owner_id",
        "uuid",
        false,
        null,
      ],
      [
        "artifact_id",
        "uuid",
        false,
        null,
      ],
      [
        "revision",
        "integer",
        false,
        null,
      ],
      [
        "content_hash",
        "text",
        false,
        null,
      ],
      [
        "title",
        "text",
        false,
        "''::text",
      ],
      [
        "type",
        "text",
        false,
        "''::text",
      ],
      [
        "tags",
        "text[]",
        false,
        "'{}'::text[]",
      ],
      [
        "path",
        "text",
        false,
        "''::text",
      ],
      [
        "gate_status",
        "text",
        true,
        null,
      ],
      [
        "knowledge_status",
        "text",
        true,
        null,
      ],
      [
        "raw_body",
        "text",
        false,
        "''::text",
      ],
      [
        "analyzer_version",
        "text",
        true,
        null,
      ],
      [
        "projection_hash",
        "text",
        false,
        null,
      ],
      [
        "updated_at",
        "timestamp with time zone",
        false,
        "now()",
      ],
    ],
    primaryKey: [
      "corpus_key",
      "owner_id",
      "artifact_id",
      "revision",
    ],
    uniques: [],
    foreignKeys: [],
    checks: [
      "CHECK ((revision > 0))",
    ],
    indexes: [],
    comment: null,
    columnComments: {},
  },
};
