/**
 * Turning a `Record<string, TableTarget>` into the committed source: `schema-target.ts` at the
 * repository root plus, since one file holding all 67 tables would clear the 700-line ceiling,
 * `schema-target/part-N.ts` modules it assembles.
 *
 * Deterministic by construction: table names are sorted before anything is packed into a file,
 * every object's keys are written in the fixed order the caller builds them in (`orderedTable`
 * below), and the packing itself is a stable left-to-right greedy fill — the same catalog always
 * produces the same files, byte for byte, however many parts it takes.
 */
import type { ForeignKeyTarget, TableTarget } from "./types.ts";

interface GeneratedFile { path: string; content: string }

/** Leaves headroom under the 700-line ceiling for each part file's header, import and
 *  wrapping `export const … = { … };` lines. */
const LINE_BUDGET = 640;

function quote(s: string): string {
  return JSON.stringify(s);
}

function propKey(k: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : quote(k);
}

/** A JSON-shaped value (string, number, boolean, null, array or plain object) rendered as a TS
 *  literal. Object keys are written in the iteration order the caller gave them — this is what
 *  `orderedTable` below uses to fix the field order the contract lists. */
function serializeValue(v: unknown, indent: string): string {
  if (v === null) return "null";
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  if (typeof v === "string") return quote(v);
  const inner = `${indent}  `;
  if (Array.isArray(v)) {
    if (v.length === 0) return "[]";
    return `[\n${v.map((x) => `${inner}${serializeValue(x, inner)},`).join("\n")}\n${indent}]`;
  }
  const entries = Object.entries(v as Record<string, unknown>);
  if (entries.length === 0) return "{}";
  const items = entries.map(([k, val]) => `${inner}${propKey(k)}: ${serializeValue(val, inner)},`).join("\n");
  return `{\n${items}\n${indent}}`;
}

/** The contract's own field order — fixed here once, rather than left to `Object.keys` on
 *  whatever `catalog.ts` happened to build. */
function orderedTable(t: TableTarget): Record<string, unknown> {
  const fk = (f: ForeignKeyTarget) => ({
    columns: f.columns, refTable: f.refTable, refColumns: f.refColumns,
    onDelete: f.onDelete, deferrable: f.deferrable,
  });
  return {
    columns: t.columns,
    primaryKey: t.primaryKey,
    uniques: t.uniques,
    foreignKeys: t.foreignKeys.map(fk),
    checks: t.checks,
    indexes: t.indexes,
    comment: t.comment,
    columnComments: t.columnComments,
  };
}

/** `schema-target.ts` plus the `schema-target/part-N.ts` files it assembles, none of them
 *  written to disk here — the caller decides whether this is a regeneration or a `--check`. */
export function generateFiles(tables: Record<string, TableTarget>): GeneratedFile[] {
  const names = Object.keys(tables).sort();
  const blocks = names.map((name) => ({
    name,
    text: `  ${propKey(name)}: ${serializeValue(orderedTable(tables[name]), "  ")},`,
  }));

  const chunks: { name: string; text: string }[][] = [];
  let current: { name: string; text: string }[] = [];
  let lines = 0;
  for (const b of blocks) {
    const blockLines = b.text.split("\n").length;
    if (current.length > 0 && lines + blockLines > LINE_BUDGET) {
      chunks.push(current);
      current = [];
      lines = 0;
    }
    current.push(b);
    lines += blockLines;
  }
  if (current.length > 0) chunks.push(current);

  const files: GeneratedFile[] = [];
  const partNames = chunks.map((_, i) => `TABLES_${i + 1}`);
  chunks.forEach((chunk, i) => {
    const n = i + 1;
    files.push({
      path: `schema-target/part-${n}.ts`,
      content: `/**\n`
        + ` * Generated by \`scripts/schema-target-extract.ts\` — part ${n} of ${chunks.length} of the\n`
        + ` * baseline catalog. Do not edit by hand; regenerate with the extractor.\n`
        + ` */\n`
        + `import type { TableTarget } from "../scripts/schema/types.ts";\n\n`
        + `export const ${partNames[i]}: Record<string, TableTarget> = {\n`
        + `${chunk.map((b) => b.text).join("\n")}\n`
        + `};\n`,
    });
  });

  const imports = chunks.map((_, i) => `import { TABLES_${i + 1} } from "./schema-target/part-${i + 1}.ts";`).join("\n");
  const spread = partNames.map((n) => `...${n}`).join(", ");
  files.push({
    path: "schema-target.ts",
    content: `/**\n`
      + ` * The frozen baseline catalog: ${names.length} design tables, extracted by\n`
      + ` * \`scripts/schema-target-extract.ts\` from a fresh \`services/gateway/migrations/001_init.sql\`\n`
      + ` * run. \`schema_migration\` and the three \`search_*_default\` partitions are excluded — see\n`
      + ` * \`scripts/schema/catalog.ts\`.\n`
      + ` *\n`
      + ` * Do not edit by hand; regenerate with the extractor and let \`--check\` confirm the tree\n`
      + ` * still matches it.\n`
      + ` */\n`
      + `import type { SchemaTarget } from "./scripts/schema/types.ts";\n`
      + `${imports}\n\n`
      + `export const SCHEMA_TARGET: SchemaTarget = {\n`
      + `  phase: 0,\n`
      + `  tables: { ${spread} },\n`
      + `};\n`,
  });
  return files;
}
