import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { validateJudgments } from '../scripts/tenant-info/benchmark.ts';
const rows = (p: string) => readFileSync(p,'utf8').trim().split('\n').map(s => JSON.parse(s));
const q = rows('testing/tenant-info/queries.jsonl');
const r = rows('testing/tenant-info/qrels.jsonl');
assert.equal(validateJudgments(q,r).ok, true);
assert.equal(validateJudgments(q.slice(1),r).ok, false);
const badGrade = structuredClone(r); badGrade[0].grade = 7;
assert.equal(validateJudgments(q,badGrade).ok, false);
const badSplit = structuredClone(q); badSplit[0].split = 'unknown';
assert.equal(validateJudgments(badSplit,r).ok, false);
const leaked = structuredClone(q);
const dev = leaked.find(x => x.split === 'dev');
const held = leaked.find(x => x.split === 'held-out');
assert.ok(dev && held); held.family = dev.family;
assert.equal(validateJudgments(leaked,r).ok, false);
assert.equal(validateJudgments(q,[]).ok, false);
const orphan = structuredClone(r); orphan[0].query_id = 'missing-query';
assert.equal(validateJudgments(q,orphan).ok, false);
console.log('tenant-info-qrels-integrity: ok');
